name: Check URLs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check_urls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install requests
      - name: Check URLs
        run: python ./check_urls.py
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if ! git diff --exit-code --quiet HEAD --; then
            git commit -m "Update CSV at $(date +"%Y-%m-%d %H:%M:%S %Z")"
            git push
          fi
